function Hd = Bandpass_GeneralizedEquiripple_FIR_filter
%BANDPASS_GENERALIZEDEQUIRIPPLE_FIR_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 25-Oct-2023 08:09:36

% Generalized REMEZ FIR Bandpass filter designed using the FIRGR function.

% All frequency values are normalized to 1.

Fstop1 = 0.45;            % First Stopband Frequency
Fpass1 = 0.48;            % First Passband Frequency
Fpass2 = 0.52;            % Second Passband Frequency
Fstop2 = 0.55;            % Second Stopband Frequency
Dstop1 = 0.01;            % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.01;            % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the coefficients using the FIRGR function.
b  = firgr('minorder', [0 Fstop1 Fpass1 Fpass2 Fstop2 1], [0 0 1 1 0 ...
           0], [Dstop1 Dpass Dstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
