function Hd = Bandpass_Elliptic_IIR_filter
%BANDPASS_ELLIPTIC_IIR_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 25-Oct-2023 08:07:50

% Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are normalized to 1.

Fstop1 = 0.45;    % First Stopband Frequency
Fpass1 = 0.48;    % First Passband Frequency
Fpass2 = 0.52;    % Second Passband Frequency
Fstop2 = 0.55;    % Second Stopband Frequency
Astop1 = 40;      % First Stopband Attenuation (dB)
Apass  = 1;       % Passband Ripple (dB)
Astop2 = 40;      % Second Stopband Attenuation (dB)
match  = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
